import os
import psycopg2
import time
import logging
from typing import Any, Generator

logger = logging.getLogger("api.db")

def _get_env(*keys: str, default: str) -> str:
    for key in keys:
        value = os.getenv(key)
        if value:
            return value
    return default

def _connect_with_retries(host: str, port: int, db_name: str, user: str, password: str):
    max_retries = int(_get_env("POSTGRES_CONNECT_RETRIES", default="10"))
    retry_delay_seconds = float(_get_env("POSTGRES_RETRY_DELAY_SECONDS", default="1"))

    for attempt in range(1, max_retries + 1):
        try:
            logger.info(
                "event=db_connect host=%s port=%s db=%s user=%s attempt=%s/%s",
                host, port, db_name, user, attempt, max_retries,
            )
            return psycopg2.connect(
                host=host,
                port=port,
                dbname=db_name,
                user=user,
                password=password,
            )
        except psycopg2.OperationalError:
            if attempt == max_retries:
                raise

            sleep_seconds = retry_delay_seconds * attempt
            logger.warning(
                "event=db_connect_retry host=%s db=%s attempt=%s/%s wait_seconds=%.2f",
                host, db_name, attempt, max_retries, sleep_seconds,
            )
            time.sleep(sleep_seconds)

def _get_postgres_connection_server(host: str, db_name: str):   
    host = _get_env("POSTGRES_HOST", "DB_POSTGRESDB_HOST", default=host)
    port = int(_get_env("POSTGRES_PORT", "DB_POSTGRESDB_PORT", default="5432"))
    db_name = _get_env("POSTGRES_DB_NAME", "DB_POSTGRESDB_DATABASE", default=db_name)
    user = _get_env("POSTGRES_USER_NAME", "DB_POSTGRESDB_USER", default="userIAjupiter")
    password = _get_env("POSTGRES_PASSWORD_VALUE", "DB_POSTGRESDB_PASSWORD", default="Qazwsx12")
    return _connect_with_retries(host, port, db_name, user, password)

# Crea la tabla "tasks" en la base de datos si no existe, con las columnas id, titulo, contenido, completada, deadline, created_at y updated_at. La columna id es una clave primaria autoincremental, titulo es un campo de texto obligatorio, contenido es un campo de texto opcional, completada es un campo booleano que indica si la tarea está completada o no (por defecto es false), deadline es un campo de fecha y hora opcional que indica la fecha límite para completar la tarea, created_at es un campo de fecha y hora que se establece automáticamente con la fecha y hora actual cuando se crea la tarea, y updated_at es un campo de fecha y hora que se establece automáticamente con la fecha y hora actual cada vez que se actualiza la tarea.
# si el script de inicio falla al crear el contenedor de postgres 
def init_db() -> None:
    query = """
    CREATE TABLE IF NOT EXISTS tasks (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_padre BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE,
        titulo VARCHAR(255) NOT NULL,
        id_user BIGINT REFERENCES public.users(id) ON UPDATE CASCADE,
        contenido TEXT,
        completada BOOLEAN DEFAULT FALSE,
        startline TIMESTAMPTZ,
        deadline TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    )
    """
    with _get_postgres_connection_server(host="postgres", db_name="dbmemori") as connection:
        with connection.cursor() as cursor:
            cursor.execute(query)
        connection.commit()
    logger.info("event=init_db table=tasks status=ready")
    
# Carga la base de datos 
def get_db() -> Generator[Any, None, None]:
    connection = None   # _get_postgres_connection_server(host="postgres", db_name="dbmemori")
    try:
        yield connection
    finally:
        connection.close()    

# Carga la base de datos productos
def get_db_products() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server(host="postgres", db_name="mainproduct")
    try:
        yield connection
    finally:
        connection.close()    

def get_db_memori() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server(host="postgres", db_name="dbmemori")
    try:
        yield connection
    finally:
        connection.close()                    

def get_db_users() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server(host="postgres", db_name="dbmemori")
    try:
        yield connection
    finally:
        connection.close()             

def get_db_tasks() -> Generator[Any, None, None]:
    connection = _get_postgres_connection_server(host="postgres", db_name="dbmemori")
    try:
        yield connection
    finally:
        connection.close()           