-- Crear usuario postgres si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'postgres') THEN
      CREATE ROLE postgres WITH LOGIN PASSWORD 'Qazwsx12' SUPERUSER;
   END IF;
END
$$;

-- Crear usuario userIAjupiter si no existe
DO
$$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'userIAjupiter') THEN
      CREATE ROLE "userIAjupiter" WITH LOGIN PASSWORD 'Qazwsx12';
   END IF;
END
$$;

-- Crear base de datos y asignar propietario
SELECT 'CREATE DATABASE "mainproduct" OWNER "userIAjupiter"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'mainproduct')\gexec

GRANT ALL PRIVILEGES ON DATABASE "mainproduct" TO "userIAjupiter";
GRANT CONNECT ON DATABASE "mainproduct" TO "userIAjupiter";

\connect mainproduct

GRANT USAGE ON SCHEMA public TO "userIAjupiter";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "userIAjupiter";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "userIAjupiter";

-- Crear base de datos de memoria para los agentes IADeepSeek y asignar propietario
\connect postgres

SELECT 'CREATE DATABASE "dbmemori" OWNER "userIAjupiter"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'dbmemori')\gexec

GRANT ALL PRIVILEGES ON DATABASE "dbmemori" TO "userIAjupiter";
GRANT CONNECT ON DATABASE "dbmemori" TO "userIAjupiter";

\connect dbmemori

GRANT USAGE ON SCHEMA public TO "userIAjupiter";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "userIAjupiter";
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "userIAjupiter";

DO
$$
BEGIN
    CREATE TABLE IF NOT EXISTS public.users (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre VARCHAR(255) NOT NULL,
        apellido VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        descripcion VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        status INTEGER DEFAULT 0,
        startline TIMESTAMPTZ,
        deadline TIMESTAMPTZ,        
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS public.tasks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_padre BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE,
        titulo VARCHAR(255) NOT NULL,
        id_user BIGINT REFERENCES public.users(id) ON UPDATE CASCADE,
        contenido TEXT,
        completada BOOLEAN DEFAULT FALSE,
        startline TIMESTAMPTZ,
        deadline TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS public.proms
    (
        id_prom BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre character(250) COLLATE pg_catalog."default" NOT NULL,
        prom character varying COLLATE pg_catalog."default",
        status integer DEFAULT 0,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP  
    );

END
$$;


\connect mainproduct

-- SEQUENCE: 
--  para crear autonumericos en la tabla de productos
DO
$$
BEGIN
	-- DROP VIEW  IF EXISTS public.ultimos_productos_creados;
    -- DROP TABLE IF EXISTS public.productos;
    -- DROP TABLE IF EXISTS public.markets_catalogues;
    -- DROP TABLE IF EXISTS public.markets;    
    -- DROP TABLE IF EXISTS public.catalogues_products;    
    -- DROP TABLE IF EXISTS public.catalogues;    
    -- DROP TABLE IF EXISTS public.clients;    
    -- DROP TABLE IF EXISTS public.type_client;    
    -- DROP TABLE IF EXISTS public.type_funding_source;    
    -- DROP TABLE IF EXISTS public.type_catalog;
    -- DROP TABLE IF EXISTS public.currency;
    -- DROP TABLE IF EXISTS public.properties;
    -- DROP TABLE IF EXISTS public.error_log;

    CREATE TABLE IF NOT EXISTS public.error_log
    (
        pk_error BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        error_title character varying COLLATE pg_catalog."default",
        error_description character varying COLLATE pg_catalog."default",
        create_date timestamp with time zone,
        pfk_user integer
    );

    CREATE TABLE IF NOT EXISTS public.properties
    (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        property character varying(500) COLLATE pg_catalog."default" NOT NULL,
        value character varying(500) COLLATE pg_catalog."default",
        valueint bigint,
        valuedate timestamp without time zone,
        creation_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint NOT NULL DEFAULT 1,
        last_update timestamp with time zone,
        CONSTRAINT propertyunique UNIQUE (property)
    );

    -- Crea la lista de tipos de moneda
    CREATE TABLE IF NOT EXISTS public.currency
    (
        pk_currency BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default",
        symbol character varying(3) COLLATE pg_catalog."default"
    );

    -- Crea la lista de tipos de catalogo
    -- catalogos de temporada, catalogos de oferta, catalogos de lanzamiento, etc.
    -- catalogos de gratis, catalogos de pago, etc.

    CREATE TABLE IF NOT EXISTS public.type_catalog
    (
        pk_type_catalog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default"
    );

    -- Crea la lista de tipos de fuente de financiamiento
    -- financiamiento propio, financiamiento externo, financiamiento mixto, etc.

    CREATE TABLE IF NOT EXISTS public.type_funding_source
    (
        pk_type_funding_source BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default"
    );

    -- Crea la lista de tipos de cliente
    -- clientes prospectos, provedores, suppliers, clientes internos, etc.

    CREATE TABLE IF NOT EXISTS public.type_client   
    (
        pk_type_client BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default"
    );

    -- Crea la lista de clientes

    CREATE TABLE IF NOT EXISTS public.clients
    (
        pk_client BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name character varying(250) COLLATE pg_catalog."default",
        description character varying(255) COLLATE pg_catalog."default",
        fk_type_client bigint DEFAULT 1,
        creation_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
    );

    -- Crea la tabla de catalogos y su relación con los productos-.
    -- Un catalogo es una lista de productos que se pueden mostrar en un mercado, y un producto solo puede estar en un catalogo, 
    --esto para evitar confusiones en la estadistica de los productos.

    CREATE TABLE IF NOT EXISTS public.catalogues
    (
        pk_catalog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_catalog character varying(250) COLLATE pg_catalog."default" NOT NULL,
        start_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        end_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_type_catalog integer DEFAULT 1,
        creation_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
    );

    -- Tabla intermedia para relacionar catalogos con productos (muchos a muchos)
    -- un producto solo puede estar en un catalogo.
    -- esto garantiza que los productos tengan una estadistica limpia 
    -- ya que un producto en dos catalogos puede generar confusiones en la estadistica.

    CREATE TABLE IF NOT EXISTS public.catalogues_products
    (
        pk_catalog_product BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pk_catalog bigint NOT NULL,
        pk_product bigint NOT NULL,
        creation_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint NOT NULL DEFAULT 1
    );

    -- Crea la tabla de mercados en donde la aplicacion puede trabajar
    -- y analizar los productos.

    CREATE TABLE IF NOT EXISTS public.markets
    (
        pk_market BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name_market character varying COLLATE pg_catalog."default",
        disabled boolean NOT NULL DEFAULT false,
        link bit varying,
        description character varying(255) COLLATE pg_catalog."default",
        creation_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
    );

    -- Tabla intermedia para relacionar mercados con catalogos (muchos a muchos)
    -- esta tabla permite guardar los clientes que pueden comprar en cada mercado,
    -- y que catalogos puedes mostrarse en cada mercado.

    CREATE TABLE IF NOT EXISTS public.markets_catalogues
    (
        pk_market_catalog BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        fk_market bigint NOT NULL DEFAULT 1,
        fk_catalog bigint NOT NULL DEFAULT 1,
        disabled boolean DEFAULT false,
        fk_client_origin bigint,
        fk_client_destination bigint,
        fk_type_funding_source integer DEFAULT 1,
        creation_date time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        last_update time with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
        fk_last_update_user bigint DEFAULT 1
	);

    -- Crea la tabla de productos y su relacion con los catalogos
    -- Solo se permite un producto con el mismo cdgo_producto_externo, pero pueden haber productos sin este codigo, 
    -- por eso no se pone como NOT NULL, pero si se crea un indice unico para este campo. 
    -- Esto es para permitir tener productos sin codigo externo, pero evitar tener dos productos con el mismo codigo externo.

    -- El campo cdgo_producto_externo es para relacionar los productos con los productos de los proveedores, 
    -- ya que el pk_product es un id interno que no se comparte con los proveedores. 

    -- De esta forma, si se tiene el cdgo_producto_externo, se puede relacionar el producto con el producto del proveedor, 
    -- y si no se tiene, se puede relacionar por el nombre del producto o por otros campos.

    -- Esto es importante para poder actualizar los productos con la información de los proveedores, 
    -- ya que el cdgo_producto_externo es el campo que se utiliza para identificar los productos de los proveedores. 
    -- Si no se tiene el cdgo_producto_externo, se pueden tener problemas para actualizar los productos con la información de los proveedores, 
    -- ya que no se sabe a qué producto del proveedor corresponde cada producto de la base de datos.

    CREATE TABLE IF NOT EXISTS public.productos
    (
        pk_product BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        cdgo_producto_externo character varying(200) COLLATE pg_catalog."default",
        name_product character(200) COLLATE pg_catalog."default" NOT NULL,
        description_product character varying(1000) COLLATE pg_catalog."default",
        disabled boolean NOT NULL DEFAULT false,
        price money DEFAULT 0,
        unit integer DEFAULT 1,
        final_price money DEFAULT 0,
        discount money DEFAULT 0,
        discount_end_date timestamp with time zone,
        fk_currency integer DEFAULT 1,
        currency character varying(50) COLLATE pg_catalog."default",
        user_rating real DEFAULT 0,
        link character varying(255) COLLATE pg_catalog."default",
        creation_date timestamp with time zone,
        fk_last_update_user bigint DEFAULT 1,
        last_update timestamp with time zone,
        supplier character varying(200) COLLATE pg_catalog."default"
    );

    -- Crea una secuencia para el campo id de productos si no existe y asigna el propietario
    -- en caso de descartar el id

    IF to_regclass('public.productos') IS NOT NULL THEN
        -- DROP SEQUENCE IF EXISTS public.productos_id_seq;

        -- CREATE SEQUENCE IF NOT EXISTS public.productos_id_seq
        --     INCREMENT 1
        --     START 1
        --     MINVALUE 1
        --     MAXVALUE 9223372036854775807
        --     CACHE 1;

        -- ALTER SEQUENCE public.productos_id_seq
        --     OWNED BY public.productos.pk_product;

        -- ALTER SEQUENCE public.productos_id_seq
        --     OWNER TO "userIAjupiter";

        -- llave de produtos externo
        CREATE UNIQUE INDEX IF NOT EXISTS ux_productos_cdgo_producto_externo
        ON public.productos (cdgo_producto_externo)
        WHERE cdgo_producto_externo IS NOT NULL;
    END IF;

    CREATE OR REPLACE VIEW public.ultimos_productos_creados
    AS
    WITH max_date AS (
            SELECT max(productos.last_update) AS max_last_update
            FROM productos
            )
    SELECT TRIM(BOTH FROM p.cdgo_producto_externo) AS cdgo_producto_externo,
        TRIM(BOTH FROM p.name_product) AS name_product,
        TRIM(BOTH FROM p.description_product) AS description_product,
        TRIM(BOTH FROM p.supplier) AS supplier,
        p.last_update
    FROM productos p
        JOIN max_date md ON p.last_update >= (md.max_last_update - '2 days'::interval) AND p.last_update <= CURRENT_TIMESTAMP
    ORDER BY (TRIM(BOTH FROM p.cdgo_producto_externo)) DESC;
END
$$;

-- Coloca las funciones de las modifi y lastudpte en las tablas

DROP FUNCTION IF EXISTS public.set_last_update_timestamp();

CREATE OR REPLACE FUNCTION public.set_last_update_timestamp()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- Al crear el registro: poner ambas fechas si vienen nulas
        IF NEW.creation_date IS NULL THEN
            NEW.creation_date := CURRENT_TIMESTAMP;
        END IF;

        IF NEW.last_update IS NULL THEN
            NEW.last_update := CURRENT_TIMESTAMP;
        END IF;

    ELSIF TG_OP = 'UPDATE' THEN
        -- En actualización: mantener la fecha de creación
        NEW.creation_date := OLD.creation_date;

        -- y actualizar solo la de última modificación
        NEW.last_update := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER FUNCTION public.set_last_update_timestamp()
    OWNER TO "userIAjupiter";

DO
$$
BEGIN
    IF to_regclass('public.productos') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_update_last_update ON public.productos;

        CREATE TRIGGER trg_update_last_update
        BEFORE INSERT OR UPDATE ON public.productos
        FOR EACH ROW
        EXECUTE FUNCTION public.set_last_update_timestamp();
    END IF;
END
$$;


-- ===========================================
-- 1) Adicionar herramientas geography para ArcGis
-- ===========================================
-- CREATE EXTENSION IF NOT EXISTS postgis;
-- CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
-- CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
-- CREATE EXTENSION IF NOT EXISTS postgis_raster; 
-- CREATE EXTENSION IF NOT EXISTS postgis_topology;
-- SELECT PostGIS_version();
-- SELECT inet_server_addr();


